const playlist = [
    "Aszfalttrón (2).mp3",
    "songs/Black Halo Protocol (1).mp3",
    "songs/Black Halo Protocol (2).mp3",
    "songs/Csúcsra Járok (1).mp3",
    "songs/Demon Season (1).mp3",
    "songs/Demon Season.mp3",
    "songs/Dust On The Sunday Sun (1).mp3",
    "songs/Dust On The Sunday Sun.mp3",
    "songs/Fractured Tongues, Broken Amps (1).mp3",
    "songs/Fractured Tongues, Broken Amps.mp3",
    "songs/Fénysebesség Szerelem (1).mp3",
    "songs/Gelato Dugómentes (1).mp3",
    "songs/Golden Afternoon Switch (1).mp3",
    "songs/Golden Afternoon Switch.mp3",
    "songs/Halfway To The Horizon (1).mp3",
    "songs/Halfway To The Horizon.mp3",
    "songs/Kiállok Érted (1).mp3",
    "songs/Kártyák Az Asztalon (1).mp3",
    "songs/Közös Emlékezés.mp3",
    "songs/La Dolce Vita (1).mp3",
    "songs/La Dolce Vita.mp3",
    "songs/Maradj Még Egy Percet (1).mp3",
    "songs/Maradnék Benned (1).mp3",
    "songs/Neonfényes Álmok (1).mp3",
    "songs/Nyári Fényben Táncolunk (1).mp3",
    "songs/Rise Like Thunder (1).mp3",
    "songs/Rise Like Thunder.mp3",
    "songs/Run The Gauntlet (1).mp3",
    "songs/Run The Gauntlet.mp3",
    "songs/Régi Fűzfa Árnyékában (1).mp3",
    "songs/Side of the Sun (1).mp3",
    "songs/Side of the Sun.mp3",
    "songs/Sun On My Sneakers (1).mp3",
    "songs/Sun On My Sneakers.mp3",
    "songs/Sötétből jövök.mp3",
    "songs/Velvet Afterglow (1).mp3",
    "songs/Velvet Afterglow.mp3",
    "songs/Üsd A Ritmust (2).mp3"
];
